//
//  DeveloperPreview.swift
//  AirbnbApp
//
//  Created by Khawla Zarrami on 12/11/2025.
//
import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    
    var listings:[Listing] = [
        .init(id: NSUUID().uuidString,
              owernerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["listing-4","listing-2", "listing-3","listing-1"],
              address: "124 Main ST",
              city: "Miami",
              state: "Foloria",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              type:.villa
             ),
        .init(id: NSUUID().uuidString,
              owernerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7706,
              longitude: -80.1340,
              imageURLs: ["listing-2","listing-1", "listing-3","listing-4"],
              address: "124 Main ST",
              city: "Miami",
              state: "Foloria",
              title: "Miami Beach House",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem,.tv , .kitchen , .office],
              type:.house
             ),
        .init(id: NSUUID().uuidString,
              owernerUid: NSUUID().uuidString,
              ownerName: "Steve Johnson",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 25.7650,
              longitude: -80.1936,
              imageURLs: ["listing-4","listing-2", "listing-3","listing-1"],
              address: "124 Main ST",
              city: "Miami",
              state: "Foloria",
              title: "Beautiful Miami appartment in downtown brickell",
              rating: 4.32,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony],
              type:.appartment
             ),
        
            .init(id: NSUUID().uuidString,
                  owernerUid: NSUUID().uuidString,
                  ownerName: "Harry Styles",
                  ownerImageUrl: "male-profile-photo",
                  numberOfBedrooms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 763,
                  latitude: 34.2,
                  longitude: -118.0426,
                  imageURLs: ["listing-2","listing-1", "listing-3","listing-4"],
                  address: "124 Main ST",
                  city: "Los Angeles",
                  state: "California",
                  title: "Beautiful Los Angeles home in Malibou",
                  rating: 4.32,
                  features: [.selfCheckIn, .superHost],
                  amenities: [.wifi, .alarmSystem, .pool],
                  type:.appartment
                 ),
        .init(id: NSUUID().uuidString,
              owernerUid: NSUUID().uuidString,
              ownerName: "Timothy Schalamet",
              ownerImageUrl: "male-profile-photo",
              numberOfBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 763,
              latitude: 34.1,
              longitude: -118.1426,
              imageURLs: ["listing-4","listing-3", "listing-2","listing-1"],
              address: "124 Main ST",
              city: "Los Angeles",
              state: "California",
              title: "Beautiful Los Angeles home in the Hollywood Hills",
              rating: 4.32,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .pool],
              type:.house
             )
    ]
}
